name: "Deploy to Server"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: "Build deployment code for standalone"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          local_dir: "."
          remote_dir: "/var/medusa-server"
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_medusa_server_deploy_key
          chmod 600 ~/.ssh/id_medusa_server_deploy_key
          echo "$dev_env_file" > .env
          chmod 600 .env
          rsync -avzr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_medusa_server_deploy_key -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
          ssh -i ~/.ssh/id_medusa_server_deploy_key ${remote_user}@${remote_host} -t "chmod a+x ${remote_dir}/develop.sh && ${remote_dir}/develop.sh"
          rm ~/.ssh/id_medusa_server_deploy_key